Adding ARC Support in MSI
Azure/azure-extension-foundation pull request #23
Opened 2024-12-09 17:12 UTC by norakoiralamsft

2024-12-09 17:24 UTC, jscalev requested changes

2024-12-09 17:24 UTC, jscalev commented on go.mod
> +go 1.19
While you're at it, could you please bump up the golang version to the latest?

2024-12-09 17:42 UTC, jscalev approved these changes

2024-12-13 23:04 UTC, vivlingaiah commented on msi/msi_test.go
> +	os.Setenv(identityEnvVar, "test")
Move it into a variable within the test, also use a constant that looks like a URL

2024-12-13 23:04 UTC, vivlingaiah approved these changes

2025-01-07 19:06 UTC, merged